/-
  Lutar.Frontier.Killinchu — live-intelligence -> verified-math frontier instance
  ================================================================================
  EXPERIMENTAL.  Auto-generated by the frontier pipeline; do NOT hand-edit.

  PROVENANCE (frozen, reproducible):
    source        : https://api.adsb.lol/v2/mil
    description   : adsb.lol military ADS-B (public broadcast) — the same feed
                    scraped by killinchu_backend.py.
    raw snapshot  : sha256 2c1b4bc0255d0a799bdbb3db4b60d7d8fc0622843861fb7d8091203c539c4b24
    feed `now`    : 1781145219001
    generated     : 2026-06-11T02:35:53Z

  MODEL:
    vertex   : an airborne military contact with valid lat/lon/altitude.
    edge     : two contacts within 50.0 nm horizontally AND 5000 ft vertically
               (a strategic-deconfliction "must get different slots" constraint).
    subset   : largest connected component, capped at 32 vertices, contacts
               ordered by ICAO hex.

  RESULT (honest): chi(G) = 4  (PROVEN: the clique lower bound meets the coloring upper bound)

  This file imports NOTHING (Mathlib-free): every theorem closes by `decide`
  over closed Bool/Nat terms, so a bare Lean kernel checks it (sorry-free).
  The kernel verifies exactly: (1) the coloring is proper and uses K colors,
  (2) the listed vertices form a clique of size m. The chromatic-number
  interpretation (chi in [m, K]) follows from these two facts; when m < K the
  exact value is OPEN and no equality is asserted.
-/
namespace Lutar.Frontier.Killinchu

/-- Number of vertices (contacts) in the frozen instance. -/
def n : Nat := 6

/-- Conflict edges `(i, j)` with `i < j`, derived from the pinned snapshot. -/
def edges : List (Nat × Nat) := [(0, 1), (0, 2), (0, 5), (1, 2), (1, 5), (2, 5), (3, 4), (3, 5), (4, 5)]

/-- Greedy proper-coloring witness: `colorList[v]` is the color of vertex `v`. -/
def colorList : List Nat := [0, 1, 2, 0, 1, 3]

/-- Color of a vertex (0 outside range; all vertices are in range here). -/
def colorOf (v : Nat) : Nat := colorList.getD v 0

/-- Number of distinct colors actually used by the witness. -/
def colorsUsed : Nat := colorList.foldl (fun acc c => max acc (c + 1)) 0

/-- Declared upper bound: the coloring uses this many colors. -/
def K : Nat := 4

/-- Witness 1a: the coloring is a PROPER coloring (no edge is monochromatic). -/
theorem killinchu_coloring_proper :
    (edges.all (fun e => !(colorOf e.1 == colorOf e.2))) = true := by decide

/-- Witness 1b: the proper coloring uses exactly `K` colors (upper bound chi <= K). -/
theorem killinchu_upper_bound :
    (colorsUsed == K) = true := by decide

/-- Undirected adjacency over the frozen edge set. -/
def adj (i j : Nat) : Bool :=
  edges.any (fun e => (e.1 == i && e.2 == j) || (e.1 == j && e.2 == i))

/-- Clique witness: a set of pairwise-adjacent vertices. -/
def clique : List Nat := [0, 1, 2, 5]

/-- Size of the clique witness. -/
def cliqueSize : Nat := clique.length

/-- A list of vertices is a clique iff every distinct pair is adjacent. -/
def isClique (vs : List Nat) : Bool :=
  vs.all (fun a => vs.all (fun b => a == b || adj a b))

/-- Witness 2a: the listed vertices really are pairwise adjacent. -/
theorem killinchu_clique_valid : isClique clique = true := by decide

/-- Witness 2b: the clique has size `m` (lower bound chi >= m). -/
theorem killinchu_lower_bound : (cliqueSize == 4) = true := by decide

/-- Lower and upper bounds coincide, so the chromatic number of this frozen
    instance is exactly 4. This equality is asserted ONLY because the kernel
    verified BOTH a 4-clique and a proper 4-coloring above. -/
theorem killinchu_chromatic_exact :
    (cliqueSize == K) = true := by decide

end Lutar.Frontier.Killinchu
