import Mathlib

namespace Lutar.Putnam.P_B2

/-!
# Putnam 2025 B2

**Problem:** Let f:[0,1]→[0,∞) be strictly increasing and continuous. Let R be the
region bounded by x=0, x=1, y=0, y=f(x). Let x₁ be the x-coordinate of the centroid
of R. Let x₂ be the x-coordinate of the centroid of the solid generated by rotating R
about the x-axis. Prove that x₁ < x₂.

**Proof technique (Cauchy-Schwarz / integral inequality):**
The centroid formulas:
  x₁ = ∫₀¹ x·f(x)dx / ∫₀¹ f(x)dx
  x₂ = ∫₀¹ x·f(x)²dx / ∫₀¹ f(x)²dx   (via Pappus for solid of revolution)

We need: ∫₀¹ x·f(x)dx / ∫₀¹ f(x)dx < ∫₀¹ x·f(x)²dx / ∫₀¹ f(x)²dx

Equivalently: (∫xf)(∫f²) < (∫xf²)(∫f)
i.e., (∫xf)(∫f²) - (∫xf²)(∫f) < 0.

This is a Chebyshev-like inequality. Since f is strictly increasing:
x and f(x) are "positively associated" — the covariance is positive.
Similarly x and f(x)² are positively associated.

More precisely: define the measure μ = f(x)dx on [0,1].
Then x₁ = E_μ[x] and x₂ = E_{f·μ}[x] where f·μ has density f(x)².
Since f is strictly increasing, larger x gives larger f(x), so the measure f·μ
puts more weight on larger x, making E_{f·μ}[x] > E_μ[x].

Formally: using Chebyshev's sum inequality or the identity:
  (∫f²)(∫xf) - (∫f)(∫xf²) = -∫∫_{x<y} (y-x)(f(y)-f(x))f(x)f(y) dy dx < 0
which follows because y>x ⟹ f(y)>f(x) (strictly increasing), so all integrands > 0.

@[source] https://maa.org/wp-content/uploads/2026/02/2025OfficialSolutions.pdf
@[source] https://kskedlaya.org/putnam-archive/
@[difficulty] 2
-/

open MeasureTheory

variable (f : ℝ → ℝ)
  (hf_cont : ContinuousOn f (Set.Icc 0 1))
  (hf_nn : ∀ x ∈ Set.Icc 0 1, 0 ≤ f x)
  (hf_str_inc : StrictMonoOn f (Set.Icc 0 1))

-- The area of R (denominator of x₁)
noncomputable def area : ℝ := ∫ x in Set.Icc 0 1, f x

-- Centroid x₁
noncomputable def x₁ : ℝ := (∫ x in Set.Icc 0 1, x * f x) / area f

-- Moment of inertia (denominator of x₂, up to π)
noncomputable def area_rot : ℝ := ∫ x in Set.Icc 0 1, f x ^ 2

-- Centroid x₂ of solid of revolution
noncomputable def x₂ : ℝ := (∫ x in Set.Icc 0 1, x * f x ^ 2) / area_rot f

-- The key identity: x₂ > x₁ follows from the positivity of:
-- (∫f²)(∫xf) - (∫f)(∫xf²) 
-- which equals -∫∫_{0<x<y<1} (y-x)(f(y)-f(x))f(x)f(y) dy dx

noncomputable def key_double_integral : ℝ :=
  ∫ x in Set.Icc 0 1, ∫ y in Set.Ici x, (y - x) * (f y - f x) * f x * f y

lemma key_double_integral_pos
    (hf_pos : ∀ x ∈ Set.Ioo 0 1, 0 < f x) :
    0 < key_double_integral f := by
  sorry -- sorry_p_B2_double_integral: positivity from f strictly increasing and positive

-- The algebraic identity connecting the double integral to x₁, x₂
lemma centroid_ineq_via_double_integral
    (ha : 0 < area f) (har : 0 < area_rot f) :
    (area_rot f) * (∫ x in Set.Icc 0 1, x * f x) -
    (area f) * (∫ x in Set.Icc 0 1, x * f x ^ 2) =
    -(2 * key_double_integral f) := by
  sorry -- sorry_p_B2_identity: Fubini + algebraic manipulation

-- Main theorem
theorem putnam_B2_correct
    (hf_pos : ∀ x ∈ Set.Ioo 0 1, 0 < f x)
    (ha : 0 < area f) (har : 0 < area_rot f) :
    x₁ f < x₂ f := by
  unfold x₁ x₂
  rw [div_lt_div_iff ha har]
  -- Need: (∫ x*f) * (∫ f²) < (∫ x*f²) * (∫ f)
  -- Equivalently: (∫f²)(∫xf) - (∫f)(∫xf²) < 0
  -- Use key_double_integral_pos and centroid_ineq_via_double_integral
  have hdi := key_double_integral_pos f hf_cont hf_nn hf_str_inc hf_pos
  have hid := centroid_ineq_via_double_integral f ha har
  nlinarith [hdi, hid]

/-!
## Notes on proof sketch:
The main `putnam_B2_correct` theorem is almost REAL: it depends on
`key_double_integral_pos` (analytic, sorry) and `centroid_ineq_via_double_integral`
(Fubini swap, sorry). The final `nlinarith` step would be real if the two lemmas compile.

## Summary
- `putnam_B2_correct`: NEAR-REAL (depends on 2 lemmas) 
- `key_double_integral_pos`: TRACKED — 1 sorry (sorry_p_B2_double_integral)
- `centroid_ineq_via_double_integral`: TRACKED — 1 sorry (sorry_p_B2_identity)
- Definitions (`area`, `x₁`, `area_rot`, `x₂`, `key_double_integral`): REAL
- Sorry count: 2 (sorry_p_B2_double_integral, sorry_p_B2_identity)
-/

end Lutar.Putnam.P_B2
