#!/usr/bin/env python3
"""Sorry-discharge worker: ask Anthropic for a candidate Lean proof for each
`sorry`, writing UNVERIFIED candidates under proposals/ for PhD review.

These candidates are NOT verified to compile — the sorry-gate + Code Owner
(PhD) review + `lake build` are the verification step. This tool only proposes.

Usage: python3 propose_proof.py [--file PATH] [--max N] [--model M]
Env:   ANTHROPIC_API_KEY (required)
"""
import argparse, json, os, re, sys, urllib.request, urllib.error

TOKEN = re.compile(r"\bsorry\b")
DEFAULT_MODEL = "claude-sonnet-4-5-20250929"


def _strip(text):
    text = re.sub(r"/-.*?-/", " ", text, flags=re.S)
    return "\n".join(l.split("--")[0] for l in text.splitlines())


def sorry_files(root="."):
    out = {}
    for dp, _d, fs in os.walk(root):
        if os.sep + ".git" in dp:
            continue
        for f in fs:
            if f.endswith(".lean"):
                p = os.path.join(dp, f)
                try:
                    n = len(TOKEN.findall(_strip(open(p, encoding="utf-8", errors="replace").read())))
                except OSError:
                    n = 0
                if n:
                    out[p] = n
    return out


def ask(model, source, path):
    key = os.environ["ANTHROPIC_API_KEY"]
    sys_prompt = (
        "You are an expert Lean 4 / Mathlib proof engineer. You are given a Lean source "
        "file that contains `sorry`. Replace every `sorry` with a complete, compiling Lean 4 "
        "proof using Mathlib where appropriate. Do NOT change statements, names, or imports "
        "except to add imports strictly required by your proof. If you genuinely cannot prove "
        "a goal, leave that `sorry` in place and explain why. Return your answer as exactly one "
        "```lean fenced code block containing the FULL revised file, followed by a one-paragraph "
        "rationale outside the block."
    )
    body = {
        "model": model,
        "max_tokens": 8000,
        "system": sys_prompt,
        "messages": [{"role": "user", "content": f"File: {path}\n\n```lean\n{source}\n```"}],
    }
    req = urllib.request.Request("https://api.anthropic.com/v1/messages",
        data=json.dumps(body).encode(), method="POST")
    req.add_header("x-api-key", key)
    req.add_header("anthropic-version", "2023-06-01")
    req.add_header("content-type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=180) as r:
            data = json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        return None, f"HTTP {e.code}: {e.read().decode()[:300]}"
    text = "".join(b.get("text", "") for b in data.get("content", []))
    m = re.search(r"```lean\n(.*?)```", text, flags=re.S)
    return (m.group(1) if m else None), text


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--file")
    ap.add_argument("--max", type=int, default=1)
    ap.add_argument("--model", default=DEFAULT_MODEL)
    ap.add_argument("--out", default="proposals")
    a = ap.parse_args(argv[1:])

    if a.file:
        targets = [a.file]
    else:
        files = sorry_files(".")
        targets = sorted(files, key=lambda p: len(open(p, encoding="utf-8", errors="replace").read().splitlines()))[:a.max]

    os.makedirs(a.out, exist_ok=True)
    index = ["# Candidate proof proposals (UNVERIFIED)\n",
             f"_Generated by propose_proof.py using `{a.model}`. NOT compiled/verified — for PhD review only._\n"]
    ok = 0
    for path in targets:
        src = open(path, encoding="utf-8", errors="replace").read()
        revised, raw = ask(a.model, src, path)
        rel = path[2:] if path.startswith("." + os.sep) else path
        if revised is None:
            index.append(f"- ❌ `{rel}` — model did not return a proof ({raw[:120]})")
            print(f"[fail] {rel}: {raw[:120]}", file=sys.stderr)
            continue
        still = len(TOKEN.findall(_strip(revised)))
        outp = os.path.join(a.out, rel)
        os.makedirs(os.path.dirname(outp), exist_ok=True)
        open(outp, "w", encoding="utf-8").write(revised)
        status = "✅ candidate (0 sorry left)" if still == 0 else f"⚠️ partial ({still} sorry left)"
        index.append(f"- {status} `{rel}` → `{outp}`")
        print(f"[ok] {rel} -> {outp} ({status})")
        ok += 1
    open(os.path.join(a.out, "INDEX.md"), "w", encoding="utf-8").write("\n".join(index) + "\n")
    print(f"\nwrote {ok}/{len(targets)} proposals to {a.out}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
