import Lean.Data.Json
import Lean.Data.Json.FromToJson

/-!
# RefVectors — golden vectors cross-runtime check

Reads the Λ₉ reference vectors generated by the production TypeScript
runtime (`@workspace/ouroboros-invariant`) and verifies operational parity
between the Lean `Float` implementation and the TS implementation, on a
curated set of inputs.

**Important caveat.** `Float` is *not* kernel-verified — it is trusted at
the level of Lean's `Float` builtin (IEEE-754). The mathematical
correctness of the definition itself lives in `Lutar/Invariant.lean`
(kernel-verified):

    Λ_k(x) := (∏ xᵢ)^(1/k)

This file checks _operational_ parity between Lean and TS on golden
inputs, which is what CI needs to catch regressions in either runtime.
-/

open Lean

namespace RefVectors

/-- A single reference vector parsed from the JSON. -/
structure RefVector where
  id     : String
  axes   : Array Float
  lambda : Float

/-- Top-level shape of the reference-vectors.json file. -/
structure RefFile where
  schema    : String
  formula   : String
  k         : Nat
  vectors   : Array RefVector
  tolAbs    : Float
  tolRel    : Float

private def asFloat? : Json → Except String Float
  | .num n => .ok n.toFloat
  | _      => .error "expected a number"

private def getStr (j : Json) (k : String) : Except String String := do
  let v ← j.getObjVal? k
  v.getStr?

private def getNat (j : Json) (k : String) : Except String Nat := do
  let v ← j.getObjVal? k
  match v with
  | .num n => .ok n.toFloat.toUInt64.toNat
  | _      => .error s!"{k}: expected a number"

private def getFloat (j : Json) (k : String) : Except String Float := do
  let v ← j.getObjVal? k
  asFloat? v

private def getArr (j : Json) (k : String) : Except String (Array Json) := do
  let v ← j.getObjVal? k
  v.getArr?

/-- Parse one `RefVector` from a JSON object. -/
def parseVector (j : Json) : Except String RefVector := do
  let id     ← getStr j "id"
  let arr    ← getArr j "axes"
  let axes   ← arr.mapM asFloat?
  let lambda ← getFloat j "lambda"
  return { id, axes, lambda }

/-- Parse the full file. -/
def parseFile (raw : String) : Except String RefFile := do
  let j ← Json.parse raw
  let schema  ← getStr j "schema"
  let formula ← getStr j "formula"
  let k       ← getNat j "k"
  let tolAbs  ← getFloat j "toleranceAbs"
  let tolRel  ← getFloat j "toleranceRel"
  let vs      ← getArr j "vectors"
  let vectors ← vs.mapM parseVector
  return { schema, formula, k, vectors, tolAbs, tolRel }

/-- Λ₉ as the TS runtime computes it: `exp((1/k) Σ log xᵢ)`.
    Mathematically `(∏ xᵢ)^(1/k)`, kernel-proved in `Lutar.Invariant`. -/
def lambdaFloat (axes : Array Float) : Float := Id.run do
  if axes.isEmpty then return 0
  if axes.any (· == 0) then return 0
  let k : Float := axes.size.toFloat
  let mut logL : Float := 0
  for v in axes do
    logL := logL + Float.log v
  return Float.exp (logL / k)

/-- Compare a computed Λ to the stored one within absolute or relative tolerance. -/
def withinTol (computed stored tolAbs tolRel : Float) : Bool :=
  let d : Float := if computed > stored then computed - stored else stored - computed
  let m : Float := if computed > stored then computed else stored
  d ≤ tolAbs || d ≤ tolRel * m

/-- Main check: parse JSON, recompute every Λ, count mismatches. -/
def checkFile (path : System.FilePath) : IO UInt32 := do
  let raw ← IO.FS.readFile path
  match parseFile raw with
  | .error e =>
      IO.eprintln s!"parse error: {e}"
      return 1
  | .ok f => do
      IO.println s!"schema:    {f.schema}"
      IO.println s!"formula:   {f.formula}"
      IO.println s!"k:         {f.k}"
      IO.println s!"vectors:   {f.vectors.size}"
      IO.println s!"tolerance: abs={f.tolAbs} rel={f.tolRel}"
      IO.println ""
      let mut bad : Nat := 0
      for v in f.vectors do
        let l   := lambdaFloat v.axes
        let ok  := withinTol l v.lambda f.tolAbs f.tolRel
        let mark := if ok then "OK   " else "FAIL "
        IO.println s!"{mark} {v.id}  stored={v.lambda}  computed={l}"
        if !ok then bad := bad + 1
      IO.println ""
      if bad = 0 then
        IO.println s!"PASS — all {f.vectors.size} vectors agree within tolerance"
        return 0
      else
        IO.eprintln s!"FAIL — {bad} of {f.vectors.size} vectors out of tolerance"
        return 1

end RefVectors
