/-
Copyright © 2026 Stephen P. Lutar Jr. (SZL Holdings).
Released under the Apache-2.0 License.

# Gleason mod-8 (V17 §XVII obligation)

Gleason's theorem (1971): every doubly-even self-dual binary linear code has
length divisible by 8.

This is the SZL governance analog of the "8-receipt closure invariant" claim
in v17 §XVII — that codes admissible under SZL gate-receipt discipline must
have length 8·m for some m ∈ ℕ.

## Mathematical content

A binary linear code C of length n is doubly-even if every codeword has
Hamming weight ≡ 0 (mod 4), and self-dual if C = C⊥ under the standard
mod-2 inner product. Gleason's 1971 proof uses the MacWilliams identity to
show that the weight enumerator W_C(x,y) must be invariant under both the
substitution (x,y) ↦ ((x+y)/√2, (x-y)/√2) (MacWilliams identity for
self-dual codes) and (x,y) ↦ (x, iy) (doubly-even condition). These two
invariances generate a finite group G of order 192 whose ring of invariants is
generated by g₈ = x⁸ + 14x⁴y⁴ + y⁸ (degree 8) and a degree-24 element —
hence the minimum possible non-trivial degree forces n ≡ 0 (mod 8).

## Citations

  - Gleason, A. M. (1971). "Weight polynomials of self-dual codes and the
    MacWilliams identities." Actes du Congrès International des Mathématiciens
    (Nice, 1970), Vol. 3, 211–215. Gauthier-Villars, Paris.
  - MacWilliams, F. J. (1963). "A theorem on the distribution of weights in a
    systematic code." Bell System Technical Journal 42(1):79–94.
    DOI 10.1002/j.1538-7305.1963.tb04003.x.
  - MacWilliams, F. J. & Sloane, N. J. A. (1977). The Theory of Error-Correcting
    Codes. North-Holland, §19.3, Theorem 19.4.
  - Conway, J. H. & Sloane, N. J. A. (1999). Sphere Packings, Lattices and
    Groups. 3rd ed., Springer, §7.2.
  - Huffman, W. C. & Pless, V. (2003). Fundamentals of Error-Correcting Codes.
    Cambridge UP, §7.6.
-/
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.BigOperators.Group.Finset
import Mathlib.Data.Finset.Card

namespace Lutar.Gates

open Finset

-- ============================================================
-- §1  Basic types
-- ============================================================

/-- A binary linear code of length n is modelled as a predicate on
    (Fin n → ZMod 2) that is closed under coordinatewise XOR and
    contains the zero codeword.

    This is a "code-as-predicate" presentation; the ambient space is
    the additive group (ZMod 2)^n.  We do not use a Submodule here
    in order to keep the module self-contained and avoid importing the
    full LinearAlgebra hierarchy. -/
structure BinaryLinearCode (n : ℕ) where
  /-- Membership predicate for codewords. -/
  isCodeword : (Fin n → ZMod 2) → Prop
  /-- The zero vector is always a codeword. -/
  zero_mem  : isCodeword (fun _ => 0)
  /-- The set of codewords is closed under componentwise addition (XOR). -/
  add_mem   : ∀ a b, isCodeword a → isCodeword b → isCodeword (a + b)

-- ============================================================
-- §2  Hamming weight
-- ============================================================

/-- The **Hamming weight** (number of nonzero coordinates) of a binary
    vector v : Fin n → ZMod 2. -/
def hammingWeight {n : ℕ} (v : Fin n → ZMod 2) : ℕ :=
  (Finset.univ.filter (fun i => v i ≠ 0)).card

-- ============================================================
-- §3  Structural predicates
-- ============================================================

/-- A code is **doubly-even** if every codeword has Hamming weight
    divisible by 4. -/
def DoublyEven {n : ℕ} (C : BinaryLinearCode n) : Prop :=
  ∀ a, C.isCodeword a → hammingWeight a % 4 = 0

/-- The mod-2 inner product (Euclidean dot product mod 2) on
    (Fin n → ZMod 2). -/
def dotMod2 {n : ℕ} (a b : Fin n → ZMod 2) : ZMod 2 :=
  ∑ i, a i * b i

/-- A code is **self-dual** if it coincides with its dual:
    C = C⊥ = { a | ∀ c ∈ C, ⟨a, c⟩₂ = 0 }. -/
def SelfDual {n : ℕ} (C : BinaryLinearCode n) : Prop :=
  ∀ a, C.isCodeword a ↔ ∀ b, C.isCodeword b → dotMod2 a b = 0

-- ============================================================
-- §4  Proved auxiliary lemmas (0 sorry)
-- ============================================================

/-- **Auxiliary lemma (PROVED).** The zero codeword has Hamming weight 0.

    Proof: the filter `{i | 0 ≠ 0}` is empty, so its cardinality is 0. -/
theorem hammingWeight_zero {n : ℕ} :
    hammingWeight (fun _ : Fin n => (0 : ZMod 2)) = 0 := by
  simp [hammingWeight]

/-- **Auxiliary lemma (PROVED).** 0 ≡ 0 (mod 4).

    Proof: by kernel-checked definitional computation (`decide`). -/
theorem zero_weight_mod_4 : (0 : ℕ) % 4 = 0 := by decide

/-- **Auxiliary lemma (PROVED).** The zero codeword has Hamming weight
    ≡ 0 (mod 4), confirming that the doubly-even condition is vacuously
    satisfied for the all-zeros codeword.

    Proof: chain of the two lemmas above. -/
theorem zero_codeword_weight_mod_4 {n : ℕ} :
    hammingWeight (fun _ : Fin n => (0 : ZMod 2)) % 4 = 0 := by
  rw [hammingWeight_zero]

-- ============================================================
-- §5  Axiom-tagged main theorem
-- ============================================================

/-- **AXIOM-TAGGED THEOREM (Gleason 1971 length-mod-8).**

    Every non-trivial doubly-even self-dual binary linear code has
    length divisible by 8.

    **Status:** AXIOM — the full Lean proof requires polynomial-invariant
    theory (invariants of finite groups acting on polynomial rings) that is
    not yet available in Mathlib v4.13.0.  This axiom is tagged per the SZL
    Series-A doctrine: it carries explicit citation provenance and a complete
    classical proof path.

    **Classical proof sketch (Gleason 1971; MacWilliams–Sloane §19.3):**

    1. *MacWilliams identity.* For any self-dual code C of length n, the
       weight enumerator W_C(x,y) = ∑_{c ∈ C} x^{n-wt(c)} y^{wt(c)} satisfies
       W_C(x,y) = W_C((x+y)/√2, (x-y)/√2) — the MacWilliams symmetry,
       equivalently W_C is fixed by the linear substitution M₁.

    2. *Doubly-even symmetry.* If C is doubly-even, W_C(x,y) = W_C(x,iy)
       (multiplication of y by the imaginary unit i = √(−1)), i.e., W_C is
       fixed by M₂.

    3. *Group generated.* M₁ and M₂ together generate a finite group G ≤ GL₂(ℂ)
       of order 192.

    4. *Molien–Noether.* By the Molien series, the Poincaré series of the
       invariant ring ℂ[x,y]^G has denominator (1−t⁸)(1−t²⁴), so every
       invariant polynomial is a polynomial in g₈ = x⁸+14x⁴y⁴+y⁸ and
       g₂₄ (degree 24). In particular, the lowest non-constant degree in the
       invariant ring is 8.

    5. *Consequence.* W_C ∈ ℂ[x,y]^G and has total degree n; hence n ≡ 0
       (mod 8) (it must be a non-negative integer multiple of the generator
       degree 8 for non-trivial codes).

    **Lean proof path (~40h, v18 target):**
      • Formalise G as a concrete finite subgroup of GL₂(ℂ) using
        `Matrix.GeneralLinearGroup`.
      • Compute the Molien series via `MvPolynomial` invariant-ring machinery
        (expected in Mathlib post v4.13.0).
      • Conclude via a degree argument on `W_C`.

    **Citations:**
      - Gleason, A. M. (1971). "Weight polynomials of self-dual codes and the
        MacWilliams identities." Actes ICM (Nice, 1970), Vol. 3, 211–215.
      - MacWilliams & Sloane (1977). The Theory of Error-Correcting Codes.
        North-Holland, Theorem 19.4.
      - Conway & Sloane (1999). Sphere Packings, Lattices and Groups. 3rd ed.,
        Springer, §7.2.
      - Huffman & Pless (2003). Fundamentals of Error-Correcting Codes.
        Cambridge UP, §7.6. -/
axiom gleason_length_mod_8 :
    ∀ {n : ℕ} (C : BinaryLinearCode n),
      DoublyEven C →
      SelfDual C →
      (∃ a, C.isCodeword a ∧ a ≠ fun _ => (0 : ZMod 2)) →
      n % 8 = 0

end Lutar.Gates
