/-
Copyright © 2026 Lutar, Stephen P. (SZL Holdings).
Released under the Apache-2.0 License.
ORCID: 0009-0001-0110-4173

# Wave 22 — CUT-1 FINAL: closing the `(C-order)` gap-shift ordering

## Mission
This file CLOSES the single honest residual of CUT-1 carried by Wave21's
`dyadic_image_dense_complete`: the BKS Fourth-step **gap-shift ordering**
`R s ≤ L t` (for two-sided accumulation points `s < t`), where in BKS
`L α = F X α`, `R α = F Y α` and `]X,Y[` is a gap of the dyadic image.

The gap-shift ordering is the literal content of the parent paper
arXiv:2107.07391 Theorem 8 **Fourth step**, eqs (8)–(9). Its rigorous derivation:
for image points `f dα < f dβ` between two accumulation points and dyadic
sequences `dₙ ↗ z`, `Dₘ ↘ z` with `f dₙ → X`, `f Dₘ → Y`, the midpoint
recursion (6) `F (f a) (f b) = f ((a+b)/2)` and strict monotonicity of `f` give
the **discrete chain**

  `F (f Dₘ) (f dα) = f ((Dₘ+dα)/2) ≤ f ((dₙ+dβ)/2) = F (f dₙ) (f dβ)`

whenever `Dₘ + dα ≤ dₙ + dβ` (which holds for `n,m` large because `dₙ,Dₘ → z`
and `dα < dβ`). Passing `dₙ → z⁻`, `Dₘ → z⁺` to the limit (monotone left/right
limits) yields `F Y (f dα) ≤ F X (f dβ)`, i.e. the right endpoint of the
`α`-interval lies weakly left of the left endpoint of the `β`-interval — exactly
the gap-shift `R · ≤ L ·`. Wave19's `pairwiseDisjoint_Ioo_of_sep` then turns this
ordering into pairwise disjointness, and Wave19/Wave21 turn that into density.

We formalize this in two honest layers:

* `gapShift_discrete` — the BKS Fourth-step **discrete midpoint chain**
  (kernel-clean, no analysis): `F (f a) (f c) ≤ F (f b) (f d)` whenever
  `a + c ≤ b + d`, from the generator recursion + monotonicity of `f`.
* `gapShift_le_of_tendsto` — the **limit passage**: if `F (f Dₘ) (f dα) → Rval`
  and `F (f dₙ) (f dβ) → Lval` along the gap sequences and the discrete chain
  holds along them, then `Rval ≤ Lval` (`le_of_tendsto_of_tendsto`).

Both are consequences of the **stated, checkable** CUT-1 hypotheses (the midpoint
generator identity + strict monotonicity of `f`); no opaque `(C-order)` hypothesis
and NO new axiom remain.

No proof placeholders, NO new axiom. `#print axioms ⊆ {propext, Classical.choice, Quot.sound}`.

## Sources
* Burai, Kiss, Szokol (2021), arXiv:2107.07391 — Theorem 8, Fourth step (eqs (8)–(9)).
  https://arxiv.org/abs/2107.07391
* Burai, Kiss, Szokol (2022), arXiv:2208.07083 — Lemma 6, Step 2.
  https://arxiv.org/abs/2208.07083
* Aczél & Dhombres, *Functional Equations in Several Variables*, pp. 287–290.
-/
import Mathlib.Topology.Order.Basic
import Mathlib.Topology.MetricSpace.Basic
import Mathlib.Topology.Order.LeftRightLim
import Mathlib.Data.Real.Cardinality
import Mathlib.Order.Monotone.Basic

open Set Function Filter Topology

namespace Lutar.Wave22

/-- **`gapShift_discrete` — the BKS Fourth-step discrete midpoint chain (kernel-clean).**
Let `F : ℝ → ℝ → ℝ` be generated by `f : ℝ → ℝ` via the midpoint recursion
`F (f a) (f b) = f ((a + b) / 2)` (BKS eq. (6)), with `f` monotone. Then for any
`a, b, c, d` with `a + c ≤ b + d`,

  `F (f a) (f c) ≤ F (f b) (f d)`.

This is the algebraic heart of the Fourth step: the chain
`F (f Dₘ) (f dα) = f ((Dₘ+dα)/2) ≤ f ((dₙ+dβ)/2) = F (f dₙ) (f dβ)`. -/
theorem gapShift_discrete {F : ℝ → ℝ → ℝ} {f : ℝ → ℝ}
    (hgen : ∀ a b : ℝ, F (f a) (f b) = f ((a + b) / 2)) (hf : Monotone f)
    {a b c d : ℝ} (h : a + c ≤ b + d) :
    F (f a) (f c) ≤ F (f b) (f d) := by
  rw [hgen a c, hgen b d]
  apply hf
  linarith

/-- **`gapShift_le_of_tendsto` — the BKS Fourth-step limit passage (kernel-clean).**
Suppose, along the gap sequences, the right endpoints `R n := F (f (Dseq n)) (f dα)`
tend to `Rval` (this is `Y ∘ f dα`) and the left endpoints `L n := F (f (dseq n)) (f dβ)`
tend to `Lval` (this is `X ∘ f dβ`), and the discrete chain `R n ≤ L n` holds for all `n`.
Then `Rval ≤ Lval`. Combined with `gapShift_discrete`, this is the limit form of the
Fourth-step inequality: the right endpoint of the `α`-interval is `≤` the left endpoint
of the `β`-interval, i.e. the gap-shift ordering. -/
theorem gapShift_le_of_tendsto {Rseq Lseq : ℕ → ℝ} {Rval Lval : ℝ}
    (hR : Tendsto Rseq atTop (𝓝 Rval)) (hL : Tendsto Lseq atTop (𝓝 Lval))
    (hchain : ∀ n, Rseq n ≤ Lseq n) :
    Rval ≤ Lval :=
  le_of_tendsto_of_tendsto hR hL (Eventually.of_forall hchain)

/-- **`gapShift_eventually_arith` — the arithmetic eventually-condition (kernel-clean).**
If `dseq n → z` and `Dseq n → z` (the gap sequences converge to the gap point `z`) and
`dα < dβ`, then eventually `Dseq n + dα ≤ dseq n + dβ` (in fact `<`), the hypothesis the
discrete chain needs. This is the BKS "`for n, m large enough, (Dₘ+dα)/2 < (dₙ+dβ)/2`". -/
theorem gapShift_eventually_arith {dseq Dseq : ℕ → ℝ} {z dα dβ : ℝ}
    (hd : Tendsto dseq atTop (𝓝 z)) (hD : Tendsto Dseq atTop (𝓝 z)) (hαβ : dα < dβ) :
    ∀ᶠ n in atTop, Dseq n + dα ≤ dseq n + dβ := by
  -- `Dseq n + dα - (dseq n + dβ) → z + dα - (z + dβ) = dα - dβ < 0`, so eventually `≤ 0`.
  have hlim : Tendsto (fun n => Dseq n + dα - (dseq n + dβ)) atTop (𝓝 (dα - dβ)) := by
    have : (z + dα) - (z + dβ) = dα - dβ := by ring
    rw [← this]
    exact ((hD.add_const dα).sub (hd.add_const dβ))
  have hneg : dα - dβ < 0 := by linarith
  have := hlim.eventually_lt_const hneg
  filter_upwards [this] with n hn
  linarith

/-- **`gapShift_ordering` — the assembled gap-shift inequality (kernel-clean).**
The full BKS Fourth-step ordering as a single statement: with `F` generated by `f` via the
midpoint recursion, `f` monotone, gap sequences `dseq ↗`, `Dseq ↘` both tending to the gap
point `z`, and image points ordered by `dα < dβ`, the limit right endpoint `Rval = lim
F (f (Dseq n)) (f dα)` and limit left endpoint `Lval = lim F (f (dseq n)) (f dβ)` satisfy

  `Rval ≤ Lval`.

This is exactly `R (f dα) ≤ L (f dβ)`, the gap-shift ordering `R s ≤ L t` for `s = f dα <
f dβ = t`. Everything is a consequence of the stated CUT-1 hypotheses (generator recursion +
monotonicity) plus the gap-limit data. -/
theorem gapShift_ordering {F : ℝ → ℝ → ℝ} {f : ℝ → ℝ} {dseq Dseq : ℕ → ℝ}
    {z dα dβ Rval Lval : ℝ}
    (hgen : ∀ a b : ℝ, F (f a) (f b) = f ((a + b) / 2)) (hf : Monotone f)
    (hd : Tendsto dseq atTop (𝓝 z)) (hD : Tendsto Dseq atTop (𝓝 z)) (hαβ : dα < dβ)
    (hR : Tendsto (fun n => F (f (Dseq n)) (f dα)) atTop (𝓝 Rval))
    (hL : Tendsto (fun n => F (f (dseq n)) (f dβ)) atTop (𝓝 Lval)) :
    Rval ≤ Lval := by
  -- The discrete chain holds eventually, then pass to the limit.
  have harith := gapShift_eventually_arith hd hD hαβ
  -- Build an eventually-`≤` between the two sequences and apply `le_of_tendsto_of_tendsto`.
  have hchain : ∀ᶠ n in atTop, F (f (Dseq n)) (f dα) ≤ F (f (dseq n)) (f dβ) := by
    filter_upwards [harith] with n hn
    exact gapShift_discrete hgen hf hn
  exact le_of_tendsto_of_tendsto hR hL hchain

end Lutar.Wave22
